// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webapi.Models;

#nullable disable

namespace Webapi.Migrations
{
    [DbContext(typeof(IngredientContext))]
    partial class IngredientContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Webapi.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ingredient1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredient10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredient2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredient3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredient4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredient5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredient6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredient7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredient8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredient9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
